import { useState } from 'react';
import { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import { useGeolocated } from '~/lib/hooks/useGeolocated';

const Home: NextPage = () => {
  const router = useRouter();

  const [keyword, setKeyword] = useState('');
  const [userSetKeyword, setUserSetKeyword] = useState('');

  const { isAvailable } = useGeolocated();

  const handleChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setKeyword(e.target.value);
  };

  const handleClick = () => {
    setUserSetKeyword(keyword);

    router.push({
      pathname: '/search',
      query: { keyword: userSetKeyword },
    });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>現在の位置情報の近くにある飲食店を検索します</h1>
        {isAvailable && (
          <div>
            <input name="keyword" type="text" onChange={handleChange} />
            <button onClick={handleClick} disabled={!isAvailable}>
              検索
            </button>
            <p>位置情報は有効になっています</p>
          </div>
        )}
      </main>
    </>
  );
};

export default Home;
