create table "public"."favorite_shops" (
    "id" integer generated by default as identity not null,
    "uuid" uuid not null,
    "name" character varying(255) not null,
    "address" character varying(255) not null,
    "genre" character varying(20) not null,
    "url" character varying(255) not null,
    "lunch" character varying(20) not null,
    "card" character varying(20) not null,
    "created_at" timestamp with time zone,
    "updated_at" timestamp with time zone
);


CREATE UNIQUE INDEX favorite_shops_pkey ON public.favorite_shops USING btree (id);

alter table "public"."favorite_shops" add constraint "favorite_shops_pkey" PRIMARY KEY using index "favorite_shops_pkey";
alter table "public"."favorite_shops" add constraint "favorite_shops_uuid_fkey" FOREIGN KEY (uuid) REFERENCES users(id) not valid;
alter table "public"."favorite_shops" validate constraint "favorite_shops_uuid_fkey";
