create table "public"."users" (
    "id" integer generated by default as identity not null,
    "uuid" uuid not null,
    "name" character varying,
    "location" character varying,
    "profile" text,
    "created_at" timestamp with time zone,
    "updated_at" timestamp with time zone
);


CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);
CREATE UNIQUE INDEX users_uuid_key ON public.users USING btree (uuid);


alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";
alter table "public"."users" add constraint "users_uuid_fkey" FOREIGN KEY (uuid) REFERENCES auth.users(id) not valid;
alter table "public"."users" validate constraint "users_uuid_fkey";
alter table "public"."users" add constraint "users_uuid_key" UNIQUE using index "users_uuid_key";
alter table "public"."users" enable row level security;


create policy "ユーザー情報の作成は認証済みの時のみできる"
on "public"."users"
as permissive
for insert
to authenticated
with check (true);


create policy "ユーザー情報の更新は誰でもできる（認証チェ"
on "public"."users"
as permissive
for update
to public
using (true);


create policy "ユーザー情報の閲覧は誰でもできる"
on "public"."users"
as permissive
for select
to public
using (true);
